name: wallet
description: Mitum Wallet Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cryptography: ^2.0.1
  # cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  # fancy_bottom_navigation: ^0.3.3
  # page_transition: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  # persistent_bottom_nav_bar: ^4.0.2
  flutter_secure_storage: ^4.2.0
  get: ^4.1.4
  get_storage: ^2.0.2
  image_picker: ^0.8.1+3
  font_awesome_flutter: ^9.1.0
  # permission_handler: ^8.1.2
  # pin_code_fields: ^7.2.0
  qr_flutter: ^4.0.0
  # qr_code_scanner: ^0.5.1
  # secp256k1: ^0.3.0
  # web3dart: ^2.1.3
  fast_base58: ^0.2.0
  encrypt: ^5.0.0
  http: ^0.13.3
  # json_schema2: ^2.0.0+2
  dio: ^4.0.0
  flutter_dotenv: ^5.0.0
  introduction_screen: ^2.1.0
  animations: ^2.0.1
  # path_provider: ^2.0.2
  logger: ^1.0.0
  dart_jsonwebtoken: ^2.3.2
  # confetti: ^0.6.0-nullsafety
  # awesome_dialog: ^2.1.0
  local_auth: ^1.1.6
  image: ^3.0.2
  # dart_ipify: ^1.1.0
  # socket_io: ^1.0.0
  biometric_storage: ^2.0.3
  # camera: ^0.8.1+7
  # video_player: ^2.1.12
  # google_ml_kit: ^0.7.0
  # firebase_core: ^1.4.0
  # try to use
  # pinput: ^1.2.0
  # dexecve: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  test: any
  mockito: ^5.0.11
  flutter_driver: any
  # flutter_native_splash: ^1.2.0
  # flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/wallet.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - default.env
    - development.env
    - production.env

    - assets/icons/flutter.png
    - assets/images/cardGlow.png
    - assets/images/visualAid.png

    - assets/images/driver_license.png
    - assets/images/drivers_license.png
    - assets/images/drivers_license_logo.png
    - assets/images/drivers_license_template.png
    - assets/images/jejupass_logo.png
    - assets/images/jejupass.png
    - assets/images/car_box.png
    - assets/images/sk_rentacar_logo.png

    - assets/icons/benefitAuthIcon.png
    - assets/icons/benefitChainIcon.png
    - assets/icons/benefitFilletIcon.png
    - assets/icons/walletIcon.png

    - assets/images/wallet.png
    - assets/images/fullscreen.jpeg
    - assets/images/img1.jpeg
    - assets/images/img2.webp
    - assets/images/img3.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
