import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final theme = ThemeData(
  brightness: Brightness.light,
  fontFamily: GoogleFonts.notoSans().fontFamily,
  textTheme: TextTheme(
    headline1: TextStyle(fontSize: 93, letterSpacing: -1.5, color: Colors.black),
    headline2: TextStyle(fontSize: 60, letterSpacing: -0.52, color: Colors.black),
    headline3: TextStyle(fontSize: 48, letterSpacing: 0.0, color: Colors.black),
    headline4: TextStyle(fontSize: 34, letterSpacing: 0.25, color: Colors.black),
    headline5: TextStyle(fontSize: 24, letterSpacing: 0.0, color: Colors.black),
    headline6: TextStyle(fontSize: 20, letterSpacing: 0.0, color: Colors.black, fontWeight: FontWeight.w900),
    subtitle1: TextStyle(fontSize: 16, letterSpacing: 0.0, color: Colors.black),
    subtitle2: TextStyle(fontSize: 24, letterSpacing: 0.1, color: Colors.black),
    bodyText1: TextStyle(fontSize: 16, letterSpacing: 0.1, color: Colors.black),
    bodyText2: TextStyle(fontSize: 14, letterSpacing: 0.1, color: Colors.black),
    caption: TextStyle(fontSize: 13, letterSpacing: 0.0, color: Colors.black),
    overline: TextStyle(fontSize: 10, letterSpacing: 1.5, color: Colors.black),
    button: TextStyle(fontSize: 18, letterSpacing: -0.4, color: Colors.black, fontWeight: FontWeight.w700),
  ),
  primarySwatch: Colors.deepPurple,
  primaryColor: Color(0xff5a24be),
  primaryColorLight: Color(0xff5a24be),
  primaryColorDark: Color(0xff7032e0),
  accentColor: Color(0xffed742f),
);
final darkTheme = ThemeData(
  brightness: Brightness.dark,
  fontFamily: GoogleFonts.notoSans().fontFamily,
  textTheme: TextTheme(
    headline1: TextStyle(fontSize: 93, letterSpacing: -1.5, color: Colors.white),
    headline2: TextStyle(fontSize: 60, letterSpacing: -0.52, color: Colors.white),
    headline3: TextStyle(fontSize: 48, letterSpacing: 0.0, color: Colors.white),
    headline4: TextStyle(fontSize: 34, letterSpacing: 0.25, color: Colors.white),
    headline5: TextStyle(fontSize: 24, letterSpacing: 0.0, color: Colors.white),
    headline6: TextStyle(fontSize: 20, letterSpacing: 0.0, color: Colors.white, fontWeight: FontWeight.w900),
    subtitle1: TextStyle(fontSize: 16, letterSpacing: 0.0, color: Colors.white),
    subtitle2: TextStyle(fontSize: 24, letterSpacing: 0.1, color: Colors.white),
    bodyText1: TextStyle(fontSize: 16, letterSpacing: 0.1, color: Colors.white),
    bodyText2: TextStyle(fontSize: 14, letterSpacing: 0.1, color: Colors.white),
    caption: TextStyle(fontSize: 13, letterSpacing: 0.0, color: Colors.white),
    overline: TextStyle(fontSize: 10, letterSpacing: 1.5, color: Colors.white),
    button: TextStyle(fontSize: 18, letterSpacing: -0.4, color: Colors.white, fontWeight: FontWeight.w700),
  ),
  primarySwatch: Colors.purple,
  primaryColor: Color(0xff7032e0),
  primaryColorLight: Color(0xff5a24be),
  primaryColorDark: Color(0xff7032e0),
  accentColor: Color(0xffed742f),
);
